process.roles=controller
node.id=2
#internally, new ServerSocket(9093), a TCP socket waiting for connections.
listeners=CONTROLLER://:9193
#among all the listeners defined, use the one with named "CONTROLLER" for
#controller-controller communication.
controller.listener.names=CONTROLLER
controller.quorum.voters=1@localhost:9093,2@localhost:9193
# PLAINTEXT (no encryption). In production, we should use SSL.
listener.security.protocol.map=CONTROLLER:PLAINTEXT
log.dirs=C:/kafka/kafka_2.13-4.3.1/data/controller2-logs
# Default partitions when creating a topic without specifying
num.partitions=3
default.replication.factor=2